<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/"><channel><title>traceback on Jürgen Gmach</title><link>https://jugmac00.github.io/tags/traceback/</link><description>Recent content in traceback on Jürgen Gmach</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><lastBuildDate>Mon, 02 Aug 2021 14:51:04 +0200</lastBuildDate><atom:link href="https://jugmac00.github.io/tags/traceback/index.xml" rel="self" type="application/rss+xml"/><item><title>How to Make a Traceback Less Verbose in Jupyter Notebooks</title><link>https://jugmac00.github.io/til/how-to-make-a-traceback-less-verbose-in-jupyter-notebooks/</link><pubDate>Mon, 02 Aug 2021 14:51:04 +0200</pubDate><guid>https://jugmac00.github.io/til/how-to-make-a-traceback-less-verbose-in-jupyter-notebooks/</guid><description>For a project I wanted to try out something new - using Jupyter Notebook to document its XML-RPC API, so documentation and specification cannot drift apart.
This worked out great.
Except - as the API also has to handle invalid input, Jupyter Notebook shows - correctly - the traceback.
The traceback is super verbose.
request server.get_licenses(&amp;#34;not-existing-id&amp;#34;) current print out in Jupyter Notebook --------------------------------------------------------------------------- Fault Traceback (most recent call last) &amp;lt;ipython-input-5-366cceb6869e&amp;gt; in &amp;lt;module&amp;gt; ----&amp;gt; 1 server.</description></item></channel></rss>