<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/"><channel><title>travis on Jürgen Gmach</title><link>https://jugmac00.github.io/tags/travis/</link><description>Recent content in travis on Jürgen Gmach</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><lastBuildDate>Fri, 30 Oct 2020 11:57:42 +0200</lastBuildDate><atom:link href="https://jugmac00.github.io/tags/travis/index.xml" rel="self" type="application/rss+xml"/><item><title>How to Fix Broken Tests on Travis for PyPy</title><link>https://jugmac00.github.io/til/how-to-fix-broken-tests-on-travis-for-pypy/</link><pubDate>Fri, 30 Oct 2020 11:57:42 +0200</pubDate><guid>https://jugmac00.github.io/til/how-to-fix-broken-tests-on-travis-for-pypy/</guid><description>The xenial build of pypy on Travis CI links against OpenSSL 1.0.2, which causes pip install cryptography to fail with
RuntimeError: You are linking against OpenSSL 1.0.2, which is no longer supported by the OpenSSL project. To use this version of cryptography you need to upgrade to a newer version of OpenSSL. For this version only you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2. Marius found the solution, see https://github.</description></item></channel></rss>